# Generated by Django 5.2 on 2025-04-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='student',
            new_name='name',
        ),
    ]
