# Generated by Django 5.2 on 2025-04-25 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_rename_name_section_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='author_name',
            field=models.ForeignKey(default='someone', on_delete=django.db.models.deletion.CASCADE, to='task.author'),
        ),
    ]
