# Generated by Django 5.2 on 2025-04-25 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_author_books_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.author'),
        ),
    ]
